### ISSUE TITLE
Customer aggregated cart fails when customer does not have any cart.

### ISSUE THREAD

**Issue by masodu** [adobe/commerce-cif-magento-extension#5]
### Expected Behaviour
The customer aggregated cart should return a 404 when customer doesn't have a cart. 
### Actual Behaviour
BAD REQUEST is returned. 
### Reproduce Scenario (including but not limited to)
access the customer aggregated cart when customer does not have cart: `rest/V1/customer-aggregated-carts/mine?productAttributesSearchCriteria[filter_groups][0][filters][0][field]=attribute_code&productAttributesSearchCriteria[filter_groups][0][filters][0][value]=color&productAttributesSearchCriteria[filter_groups][0][filters][1][field]=attribute_code&productAttributesSearchCriteria[filter_groups][0][filters][1][value]=size`

### Attached full log:
"options": {
          "uri": "http://master-7rqtwti-7ztex4hq2b6mu.us-3.magentosite.cloud/rest/V1/customer-aggregated-carts/mine?productAttributesSearchCriteria[filter_groups][0][filters][0][field]=attribute_code&productAttributesSearchCriteria[filter_groups][0][filters][0][value]=color&productAttributesSearchCriteria[filter_groups][0][filters][1][field]=attribute_code&productAttributesSearchCriteria[filter_groups][0][filters][1][value]=size",
          "method": "GET",
          "headers": {
            "accept": "application/json",
            "content-type": "application/json; charset=utf-8",
            "pragma": "no-cache",
            "cache-control": "no-cache",
            "authorization": "Bearer g17qnwxkqvwu4uqjwlt9fb8sutu9mta5"
          },
          "json": true,
          "simple": true,
          "resolveWithFullResponse": false,
          "transform2xxOnly": false
        },
        "response": {
          "statusCode": 400,
          "body": {
            "message": "\"%fieldName\" is required. Enter and try again.",
            "parameters": {
              "fieldName": "cartId"
            }
          }

**Comment by paliarush** [comment]
The fix is ready and will be delivered to 2.3-develop of magento2 repository in the next week.

**Comment by masodu** [comment]
@paliarush have you fixed it by always creating a cart for a customer?

**Comment by masodu** [comment]
@paliarush I was confused by some deployment issues I had so pls ignore the previous comments. Looks good based on magento-2.3.0-alpha62. We can close the issue now.
