### ISSUE TITLE
AggregatedServices documentation should include REST call for obtaining guest cartId

### ISSUE THREAD

**Issue by ryanvivoli** [adobe/commerce-cif-magento-extension#6]
### Expected Behaviour
AggregatedServices documentation explains how to obtain a guest cartId using a separate REST call

### Actual Behaviour
No indication of how this is done, so a user may end up using the quote ID as saved in the DB

#### Steps to Reproduce
Go through the AggregatedServices documentation and notice that there is no step to obtain the cartId.

#### Platform and Version
Magento 2.3 graphql

#### Sample Code that illustrates the problem
N/A

#### Logs taken while reproducing problem
N/A

**Comment by masodu** [comment]
@paliarush can this be closed?
